services:
  app:
    build: .
    # image: 293210009733.dkr.ecr.ap-northeast-1.amazonaws.com/pitatoku:latest
    ports:
      - '8085:8080'
    volumes:
      - ./src/main/resources/templates:/app/src/main/resources/templates
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pika_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

      SPRING_THYMELEAF_PREFIX: file:/app/src/main/resources/templates/
      SPRING_THYMELEAF_CACHE: false
      SPRING_THYMELEAF_MODE: HTML
      SPRING_THYMELEAF_ENCODING: UTF-8
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pika_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 3
      interval: 5s
      start_period: 10s

volumes:
  db_data:
